@SecurityDemoApi_HostAddress = http://localhost:5032

### PUBLIC ENDPOINT (No Token Needed)
GET {{SecurityDemoApi_HostAddress}}/api/secure/public
Accept: application/json


### LOGIN (Generate JWT Token)
POST {{SecurityDemoApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "sejal",
  "password": "123",
  "role": "Admin",
  "department": "HR"
}


### PROFILE (Requires Token)
GET {{SecurityDemoApi_HostAddress}}/api/secure/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic2VqYWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIkRlcGFydG1lbnQiOiJIUiIsIlVzZXJJZCI6ImY1ZGZlMTJlLTI0NjktNGUyNC1iMjQwLThlOGUzMzk2ODhjZCIsImV4cCI6MTc3MjcxOTE1OSwiaXNzIjoiU2VjdXJpdHlEZW1vQXBpIiwiYXVkIjoiU2VjdXJpdHlEZW1vQ2xpZW50cyJ9.7UTXoN7yt_N2aBcjlmrT_iurGqzZCUDAexUK7iUxSKs


### ADMIN ENDPOINT
GET {{SecurityDemoApi_HostAddress}}/api/secure/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic2VqYWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIkRlcGFydG1lbnQiOiJIUiIsIlVzZXJJZCI6ImY1ZGZlMTJlLTI0NjktNGUyNC1iMjQwLThlOGUzMzk2ODhjZCIsImV4cCI6MTc3MjcxOTE1OSwiaXNzIjoiU2VjdXJpdHlEZW1vQXBpIiwiYXVkIjoiU2VjdXJpdHlEZW1vQ2xpZW50cyJ9.7UTXoN7yt_N2aBcjlmrT_iurGqzZCUDAexUK7iUxSKs


### HR ENDPOINT
GET {{SecurityDemoApi_HostAddress}}/api/secure/hr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic2VqYWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIkRlcGFydG1lbnQiOiJIUiIsIlVzZXJJZCI6ImY1ZGZlMTJlLTI0NjktNGUyNC1iMjQwLThlOGUzMzk2ODhjZCIsImV4cCI6MTc3MjcxOTE1OSwiaXNzIjoiU2VjdXJpdHlEZW1vQXBpIiwiYXVkIjoiU2VjdXJpdHlEZW1vQ2xpZW50cyJ9.7UTXoN7yt_N2aBcjlmrT_iurGqzZCUDAexUK7iUxSKs


### ADMIN + HR ENDPOINT
GET {{SecurityDemoApi_HostAddress}}/api/secure/admin-hr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic2VqYWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIkRlcGFydG1lbnQiOiJIUiIsIlVzZXJJZCI6ImY1ZGZlMTJlLTI0NjktNGUyNC1iMjQwLThlOGUzMzk2ODhjZCIsImV4cCI6MTc3MjcxOTE1OSwiaXNzIjoiU2VjdXJpdHlEZW1vQXBpIiwiYXVkIjoiU2VjdXJpdHlEZW1vQ2xpZW50cyJ9.7UTXoN7yt_N2aBcjlmrT_iurGqzZCUDAexUK7iUxSKs